name: CI/CD pipeline

on:
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize]
jobs:
  test:
    run-on : ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3

      - name : Install dependencies
        run: npm ci

      - name : Build the project
        run: npm run build

      - name : Unit tests
        run: npm test

      - name: Scan project with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: CRITICAL, HIGH, MEDIUM,LOW
