name: CI/CD pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize]

jobs:
  CI/CD_pipeline:
    runs-on: ubuntu-latest  # ✅ FIXED: was 'run-on' (typo)
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Set environment variables
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Build the project
        run: npm run build

#      - name: Unit tests
#        run: npm test

      - name: Scan project with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: CRITICAL,HIGH,MEDIUM,LOW  # ✅ FIXED: removed space before "Check failure"
